### ISSUE TITLE
vue3 directive not working

### ISSUE THREAD

**Issue by yogesh-gohil** [jonathanpmartins/v-money3#17]
I have created the v-money3 directive and use it on the input element but its not reactive its give bellow error on console 

![Screenshot 2021-06-11 at 10 07 57 AM](https://user-images.githubusercontent.com/33858419/121632415-8f22d400-ca9e-11eb-895e-5bd5b9bff114.png)

**Comment by jonathanpmartins** [comment]
@yogesh-gohil 

Would be nice to have more information about the problem. I could not find it!
Can you elaborate a [codesandbox](https://codesandbox.io/) example?

This is a working example of [directive](https://codesandbox.io/s/v-money3-use-as-directive-e7ror?file=/src/App.vue:0-919) usage.

```html
<input v-model.lazy="amount" v-money3="config" />
```

```js
import { Money3Directive } from "v-money3";
export default {
  data() {
    return {
      amount: 0,
    };
  },
  computed: {
    config() {
      return {
        decimal: ",",
        thousands: ".",
        prefix: "R$ ",
        suffix: "",
        precision: 2,
        masked: false /* doesn't work with directive */,
      };
    },
  },
  directives: {
    money3: Money3Directive,
  },
};
```

**Comment by jonathanpmartins** [comment]
Hey, @yogesh-gohil. Could you please update to the last `3.13.6` version and test if your problem persists? I made a fix for a problem that was happening if you initialized the component using a `null` value for v-model.

**Comment by jonathanpmartins** [comment]
closed by user timeout

**Comment by jonathanpmartins** [comment]
https://github.com/jonathanpmartins/v-money3/issues/19 Could this be related @yogesh-gohil @botura ?

**Comment by botura** [comment]
Probably yes, errors seen to be the same.
