### ISSUE TITLE
Error with null value

### ISSUE THREAD

**Issue by botura** [jonathanpmartins/v-money3#19]
Null value throws an error.

[https://codesandbox.io/s/v-money3-use-as-component-forked-y2qs4?file=/src/App.vue](https://codesandbox.io/s/v-money3-use-as-component-forked-y2qs4?file=/src/App.vue)

It would be nice if the component could accept it.

**Comment by jonathanpmartins** [comment]
@botura will take a look on it in the weekend! Keep throwing issues! I'm grad to solve them!

**Comment by jonathanpmartins** [comment]
Please update to the latest `3.13.8` version to get the fix. It will not return null as you tried in your code, instead, it will check null and convert it to 0 (zero).

If you want an empty input do set `allow-blank` to true. [example](https://codesandbox.io/s/v-money3-use-as-component-forked-xjxp1?file=/src/App.vue)

Thank you for reporting this issue.
