### ISSUE TITLE
update:model-value is duplicated

### ISSUE THREAD

**Issue by AndrolGenhald** [jonathanpmartins/v-money3#35]
Because `update:model-value` is emitted whenever the input is changed, and the input is changed when being formatted, `update:model-value` events are duplicated.

**Comment by jonathanpmartins** [comment]
Pull request code was introduces in this commit: https://github.com/jonathanpmartins/v-money3/commit/4760c7aee518b4487b3b8c3483f3abb4b352fa5a

I will close this issue now.
It's not solved at the moment, but will be in the next release!
Thanks!
