### ISSUE TITLE
Allow-Blank is not working on precision other than 2

### ISSUE THREAD

**Issue by mazraara** [jonathanpmartins/v-money3#37]
![image](https://user-images.githubusercontent.com/2024844/129725764-d45d108b-ca02-48bd-a455-fe7830269bfb.png)

Currently i am trying to set the precision as 0 to have it worked as just integers, however this add (auto fill) a 0 by default when the page loads.

Is there an option to disable the decimal point?

**Comment by jonathanpmartins** [comment]
Does the `allow-blank` option suit your needs?

**Comment by mazraara** [comment]
@jonathanpmartins i am using that option already

![image](https://user-images.githubusercontent.com/2024844/129822346-e58668c4-e7e2-4d27-8492-b5c9e9a3e930.png)

is there another way to say disable decimal instead of saying precision 0 ?

**Comment by jonathanpmartins** [comment]
Are you using Component or Directive?

**Comment by jonathanpmartins** [comment]
Thanks for reporting the issue. It was solved in `3.16.1`.
