### ISSUE TITLE
Precision '0' strange behavior with thousands '.'

### ISSUE THREAD

**Issue by JohnniePeixoto** [jonathanpmartins/v-money3#39]
Hello, 

I've noticed that when precision is set to 0 the result is crazy with some range of numbers. Look this example:
https://codesandbox.io/s/v-money3-use-as-component-forked-1gsou?file=/src/App.vue

I'm trying to use with thousand delimiter but only integer numbers (no precision).

**Comment by jonathanpmartins** [comment]
Solved on `3.17.1`. Thanks for reporting!
