### ISSUE TITLE
Refactor code from ES6/ES2020 to Typescript

### ISSUE THREAD

**Issue by jonathanpmartins** [jonathanpmartins/v-money3#41]

**Comment by sougiovn** [comment]
Hey @jonathanpmartins I forked the project and started this refactory, take a look [feat/refactory#41](https://github.com/gigioSouza/v-money3/tree/feat/refactory-ts%2341)

Feel free to add me on Discord `Giovane Souza#8309` if you want to discuss about what I'm doing.
I decided to help the project during my current vacations.

**Comment by jonathanpmartins** [comment]
What a good surprise!
I open this issue near 2 weeks ago but haven't had time to tackle it.
Now I think it will happen shortly.
Good initiative! Thank you...

**Comment by jonathanpmartins** [comment]
Merged in pull request https://github.com/jonathanpmartins/v-money3/pull/46
Published as `3.19.0`. Thank you very much!
