### ISSUE TITLE
Is working "v-model number modifier"?

### ISSUE THREAD

**Issue by joserick** [jonathanpmartins/v-money3#42]
Hi @jonathanpmartins 

A quick question, does the example "[v-model number](https://github.com/jonathanpmartins/v-money3#component-v-model-number-modifier-view-codesandbox)" work? is that in my browser it does not perform any interaction with the input, since I was interested in handling the "amount" as a number instead of "string" so as not to import and use the "unformat" function.

**Component v-model number modifier ([view codesandbox](https://codesandbox.io/s/v-money3-use-as-component-forked-523de?file=/src/App.vue))**

**Comment by jonathanpmartins** [comment]
Maaann... Strange Things happening! heheheh 
All tests were passing but I added some more to guarantee integrity on this issue. 
Will release a new version with a fix on `3.17.4`... Please, test it out and report any other problem!
Thanks for helping out!
