### ISSUE TITLE
Compiling error (createElementBlock) with Vue versions lower than 3.2.0

### ISSUE THREAD

**Issue by renatoberaldo** [jonathanpmartins/v-money3#44]
Hi Jonathan ... I got that error when I try to run dev.

`> node_modules/v-money3/dist/v-money3.es.js:1:124: error: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "createElementBlock"
    1 │ ...withDirectives as r,openBlock as s,createElementBlock as a,mergeProps as l}from"vue";co... `
![v-money3-error](https://user-images.githubusercontent.com/13209573/132263968-5cd74e20-6a65-4083-9e27-d9204d777034.PNG)

Could you help me?? 

Thanks bro!

**Comment by jonathanpmartins** [comment]
I need a little more help to repeat the problem here in my development environment. Perhaps a step by step description of your workflow...

Can you create a [codesandbox.io](https://codesandbox.io/) with this problem example?

What is the version that you are using?

**Comment by renatoberaldo** [comment]
Oops... I saw you are from Brazil... great!

Can I share the github project with you?

Thanks in advance,
Renato

**Comment by jonathanpmartins** [comment]
Yes you can! Send me a link and the steps to get to the error. We can speak portuguese there....

**Comment by renatoberaldo** [comment]
Ok perfect.. Thanks ;)

**Comment by jonathanpmartins** [comment]
The user was using `vue` and `@vue/compiler-sfc` version `3.0.5`. For some unknown reason at the moment the library is generating this compiler error with vue versions lower than `3.2.0`.

- vue 3.1.5 (-) problem
- vue 3.2.0 (+) ok

**Comment by renatoberaldo** [comment]
Perfect!! working now! Thanks you!!!
