### ISSUE TITLE
Export BigNumber

### ISSUE THREAD

**Issue by joserick** [jonathanpmartins/v-money3#48]
Hi @jonathanpmartins 

I hope you are well,
I'm going to take you [comment](https://github.com/joserick/v-money-spinner/issues/8#issuecomment-913921789), to ask if you could expose the BigNumber class.

Thanks in advance.

**Comment by jonathanpmartins** [comment]
You request was published in `3.20.0`.

```
import BigNumber from 'v-money3';
```

This class is currently very simple, it only has the methods needed for v-money3 to work. Feel free to open an issue or a pull request to improve upon it.
