### ISSUE TITLE
No declaration file for module 'v-money3'

### ISSUE THREAD

**Issue by gogodigimo** [jonathanpmartins/v-money3#52]
I saw in another thread that you were attempting to create definition files for this package, but it seems I'm still getting this issue. Any progress on that?

```
Could not find a declaration file for module 'v-money3'. '.../node_modules/v-money3/dist/v-money3.umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/v-money3` if it exists or add a new declaration (.d.ts) file containing `declare module 'v-money3';`
```

**Comment by jonathanpmartins** [comment]
If you need a quick fix, simply add this before the line of your import: [by stackoverflow](https://stackoverflow.com/a/55576119/3681102)
```
// @ts-ignore
```
---
In the mean time, I'm working in the problem solution. Thanks for reporting this issue!

**Comment by jonathanpmartins** [comment]
Just passing by to say I'm sorry for the delay. This time of the year it is summer south of the equator and I'm in vacations with the family until February.
If you, or someone else have a pull request, it will be appreciated. Otherwise, this will be tackled when I'm back.
Happy new year!

**Comment by jonathanpmartins** [comment]
Please update to version `3.21.0`.
Can you confirm that this issue has gone away? @gogodigimo
Thanks for the pull request @sambitevidev
