### ISSUE TITLE
Big integer literals are not available

### ISSUE THREAD

**Issue by idafoh** [jonathanpmartins/v-money3#57]
I got this error Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")

- Vue version: 3.2.31
- v-money3 version: 3.21.0

![image](https://user-images.githubusercontent.com/83906251/156997404-cb507470-29af-48f6-9c59-cea8916cf1c6.png)

**Comment by jonathanpmartins** [comment]
Yes, this is correct. The configured target should be "es2020", take a look at this post: https://www.freecodecamp.org/news/javascript-new-features-es2020/

BigInt (used by this project) is a new feature in es2020 and beyond.

**Comment by fylica** [comment]
es2020 alone is not enough to make it work. Check your browser/version list from this [table](https://caniuse.com/bigint), and adjust their versions accordingly.

**Comment by jonathanpmartins** [comment]
@fylica you are right. This is the table that I grab from caniuse.com
![Screenshot from 2022-03-19 04-00-01](https://user-images.githubusercontent.com/6137992/159111179-90553bd7-4f71-4b3a-8568-d3feda424384.png)
