### ISSUE TITLE
Error when I run my test with Jest

### ISSUE THREAD

**Issue by gabrielbarretosantoos** [jonathanpmartins/v-money3#59]
When I run my suite's test, this error it's happening (image below) 

![image](https://user-images.githubusercontent.com/47193908/161658753-891e0b3c-754b-4484-98ae-d4873bc1d32f.png)

I don't know why happened this problem :/

Now I inserted just arrow function return nothing, just for passed my test.

**Comment by gabrielbarretosantoos** [comment]
I've other error:

![image](https://user-images.githubusercontent.com/47193908/161864981-63a3b653-e472-46b8-905f-fb758c6f283d.png)

Every time I need to remove this sentence BIGINT and only then work

Any suggestion for this too?

**Comment by jonathanpmartins** [comment]
The configured target should be "es2020". I think this is similar to https://github.com/jonathanpmartins/v-money3/issues/57

**Comment by jonathanpmartins** [comment]
About the first problem, I will need more information. Could it be related to the second one?
