### ISSUE TITLE
@change evento not send value

### ISSUE THREAD

**Issue by Laranjeiras** [jonathanpmartins/v-money3#62]
@change event is not returning the value, it is returning the component.

![image](https://user-images.githubusercontent.com/6052106/172522208-7a97c9ff-f86f-4577-b417-0131a0d4a93c.png)

**Comment by jonathanpmartins** [comment]
Could you elaborate more?

If you need to get the value within the event listener function, something like this should work:

```html
<v-money3 @change="changed">
```

```javascript
changed(event) => {
  console.log(event.target.value)
}
```
