### ISSUE TITLE
running on vite, I get this error:

### ISSUE THREAD

**Issue by renatosaz** [jonathanpmartins/v-money3#67]
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

    node_modules/.pnpm/v-money3@3.21.0_vue@3.2.37/node_modules/v-money3/dist/v-money3.es.js:225:35:
      225 │       thisNum = this.getNumber() * 10n ** BigInt(diff * -1);

**Comment by jonathanpmartins** [comment]
I think you are getting this error because of `safari13`. Taking a look at [CanIUse](https://caniuse.com/?search=BigInt), it is supported only on `safari14` and beyond.

**Comment by renatosaz** [comment]
Thanks for the reply... , but I was running on chrome, not safari. . I had to change this lib, coudln't fix it at all.  regards
