### ISSUE TITLE
Automatically focus on right

### ISSUE THREAD

**Issue by SDIjeremy** [jonathanpmartins/v-money3#77]
I'd only like to type from the left hand side.
It seems the functionality is very dependent on where you click in the input.

I'd always like the user to type `1 2 [dot] 3 4` to get `$12.34`

**Comment by jonathanpmartins** [comment]
Yep, this is a feature that was requested in this issue: [#20 - behave like normal input when getting focus](https://github.com/jonathanpmartins/v-money3/issues/20).

I will create a flag to toggle the functionality on the next release.

**Comment by SDIjeremy** [comment]
thank you

**Comment by jonathanpmartins** [comment]
Published on version `3.24.0`
