### ISSUE TITLE
v-money3 with Quasar2 Error Big integer

### ISSUE THREAD

**Issue by itokia** [jonathanpmartins/v-money3#79]
Hello, when I try to use v-money3 I get the following error ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", " safari13.1")

I'm on quasar.js v2 and vue.js 3.

In the quasar.config.js file I tried to switch es2019 to es2021 without it working. I'm on firefox.

Do you have a solution for me?

**Comment by jonathanpmartins** [comment]
I think your problem is "safari13.1" vs "safari14". Try it with `safari14`. If the problem persists please come back.
