### ISSUE TITLE
Could not find a declaration file for module 'v-money3'.

### ISSUE THREAD

**Issue by pavanetti** [jonathanpmartins/v-money3#86]
I'm getting the following error message:

`
Could not find a declaration file for module 'v-money3'. 'node_modules/v-money3/dist/v-money3.mjs' implicitly has an 'any' type.
  There are types at 'node_modules/v-money3/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'v-money3' library may need to update its package.json or typings. ts(7016)
`

Node: 18.16.1
Typescript: 5.2.2
Vite: 4.5.0
Vue: 3.3.9

**Comment by jonathanpmartins** [comment]
Related to https://github.com/jonathanpmartins/v-money3/pull/84
