### ISSUE TITLE
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")

### ISSUE THREAD

**Issue by satish123satish123** [jonathanpmartins/v-money3#89]
I am getting this error

Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")

    node_modules/v-money3/dist/v-money3.mjs:107:22:
      107 │     w(this, "number", 0n);

**Comment by PWTK** [comment]
@satish123satish123  I faced the same problem, Please try [this](https://github.com/jonathanpmartins/v-money3/issues/70).

**Comment by jonathanpmartins** [comment]
The browser targets should have at minimum these entries:
```
("es2020", "safari14")
```
Change your browser targets from this:
```
("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
```
To this:
```
("chrome87", "edge88", "es2020", "firefox78", "safari14")
```
It should work!
