### ISSUE TITLE
Got error trying to use with Quasar V2

### ISSUE THREAD

**Issue by MaikonPanazzolo** [jonathanpmartins/v-money3#95]
I'm using Quasar V2 with Vue3 and I got the following error trying to use with QInput component from Quasar:

![image](https://github.com/jonathanpmartins/v-money3/assets/32369765/84cb0e03-bdc7-489b-ab98-4036b3813d03)

The way I'm declaring the mask is in a mixin boot file:

![image](https://github.com/jonathanpmartins/v-money3/assets/32369765/9193ff5e-1d70-4e9b-b4ec-4b1421449534)

Obs: I've tryed to use with a pure html input component and it's working, I mean, maybe the directive cannot access element within QInput.

**Comment by jonathanpmartins** [comment]
You are correct. It cannot be set directly on a QInput element. Take a look at this comment: https://github.com/jonathanpmartins/v-money3/issues/92#issuecomment-1972154455. It is a custom component that hooks up into QField. Hope it helps!
