### ISSUE TITLE
Directive Model Modifier not working

### ISSUE THREAD

**Issue by usmanibrahim74** [jonathanpmartins/v-money3#97]
<template>
    <div>

        <Label v-if="label" :for="id">{{ label }} {{ model }}</Label>
        <Input
            v-model.lazy="model"
            :class="[
                classes,
                errorMsg
                    ? 'border-destructive placeholder:text-destructive'
                    : '',
            ]"
            :model-modifiers="{ number: true }"
            type="text"
            :id="id"
            :placeholder="placeholder"
            :disabled="disabled"
            v-money3="{ ...config, modelModifiers: { number: true } }"
        />
        <InputError :class="['mt-2', errorMsgClasses]" :message="errorMsg" />
    </div>
</template>
config

`{
                prefix: "£",
                suffix: "",
                thousands: ",",
                decimal: ".",
                precision: 0,
                disableNegative: true,
                disabled: false,
                min: null,
                max: null,
                allowBlank: true,
                minimumNumberOfCharacters: 0,
                shouldRound: true,
                focusOnRight: false,
                masked: false,
                modelModifiers: { number: true },
            }`
          
![image](https://github.com/user-attachments/assets/5f8409dc-2ee3-43d8-bc8d-c5ae52abdabf)

**Comment by jonathanpmartins** [comment]
It seems that you are not using the directive in a native html input. This is probably the reason why you are getting into problems. In your case, it is best to use the component, not the directive.

**Comment by usmanibrahim74** [comment]
I will try it. thanks for pointing out this
